import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getDatabase,ref,onValue,get,set,push,remove,runTransaction,onDisconnect,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js';
import {firebaseConfig,roleUids} from './firebase-config.js';
import {questions} from './questions.js';
const role=document.body.dataset.role, root=document.getElementById('app');
const configured=!Object.values(firebaseConfig).some(v=>String(v).includes('PASTE_'))&&!Object.values(roleUids).some(v=>v.includes('PASTE_'));
if(!configured){root.innerHTML='<section class="panel login"><h1>설정이 필요해요</h1><p>firebase-config.js에 Firebase 설정과 A/B/운영진 UID를 입력해주세요. README.md를 참고하세요.</p></section>';throw Error('Firebase 설정 필요');}
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),S=ref(db,'session');
let session=null,sessionId=null,connected=false,offset=0,unsubs=[],presence=null,previousMessageCount=0,presenceData={};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fail=e=>{const t=document.createElement('div');t.className='toast';t.textContent=e?.message||String(e);document.body.append(t);setTimeout(()=>t.remove(),4000)};
const now=()=>Date.now()+offset;
const remain=()=>Math.max(0,(session?.endsAt||0)-now());
function cleanup(){unsubs.forEach(f=>f());unsubs=[];if(presence){onDisconnect(presence).cancel().catch(()=>{});remove(presence).catch(()=>{});presence=null;}session=null;sessionId=null;markedId=null;presenceData={};previousMessageCount=0;}
function login(){root.innerHTML=`<form class="panel login" id="login"><div class="eyebrow">BLIND DATE · ${role==='admin'?'STAFF':role}</div><h1>입장하기 💌</h1><p class="muted">운영진에게 받은 계정으로 로그인해주세요.</p><input name="email" type="email" placeholder="이메일" required autocomplete="username"><input name="password" type="password" placeholder="비밀번호" required autocomplete="current-password"><button class="primary">로그인</button><p class="error" id="loginError"></p></form>`;document.getElementById('login').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await signInWithEmailAndPassword(auth,f.email.value.trim(),f.password.value)}catch(err){document.getElementById('loginError').textContent='로그인에 실패했어요. 계정 정보를 확인해주세요.'}}}
onAuthStateChanged(auth,user=>{cleanup();if(!user){login();return}if(user.uid!==roleUids[role]){root.innerHTML='<section class="panel login"><h1>이 화면에 접근할 수 없어요.</h1><button class="secondary" id="out">로그아웃</button></section>';document.getElementById('out').onclick=()=>signOut(auth);return}mount()});
function mount(){const admin=role==='admin';root.innerHTML=admin?`<div class="shell"><header class="top"><span class="brand">💌 BLIND DATE <span class="tag">운영진</span></span><button class="logout" id="out">로그아웃</button></header><section class="panel admin"><div><div class="eyebrow">CONTROL ROOM</div><h1>오늘의 만남</h1><p class="muted" id="state"></p></div><div><div class="row">참가자 A <strong id="aPresence" class="dot">○ 대기 중</strong></div><div class="row">참가자 B <strong id="bPresence" class="dot">○ 대기 중</strong></div></div><div class="hero"><small>남은 시간</small><div class="clock" id="clock">10:00</div></div><div class="actions"><button class="primary" id="start">소개팅 시작</button><button class="secondary" id="finish">강제 종료</button><button class="danger" id="reset">다음 커플 준비</button></div><p class="notice">새 커플이 앉기 전에 두 참가자 화면을 새로고침하고 로그인 상태를 확인하세요. 초기화하면 이전 대화와 질문은 삭제됩니다.</p></section></div>`:`<div class="shell"><header class="top"><span class="brand">💌 BLIND DATE</span><span class="tag">참가자 ${role}</span></header><section class="panel chat"><div class="hero"><small>우리에게 남은 시간</small><div class="clock" id="clock">10:00</div><div class="state" id="state">운영진의 시작을 기다려주세요</div></div><div class="prompt" id="prompt"></div><div class="messages" id="messages"><div class="empty">첫 대화를 기다리는 중이에요 ✨</div></div><div><div class="questionbar"><button class="secondary" id="question">🎲 랜덤 질문 뽑기</button></div><form class="composer" id="composer"><input id="message" maxlength="300" placeholder="메시지를 입력하세요" autocomplete="off"><button class="primary" id="send">전송</button></form></div><div class="overlay" id="overlay"><div><div style="font-size:3rem">💌</div><h2 id="overlayTitle">잠시만 기다려주세요</h2><p id="overlayText">운영진이 소개팅을 시작하면 대화할 수 있어요.</p></div></div></section><button class="logout" id="out">로그아웃</button></div>`;
document.getElementById('out').onclick=()=>signOut(auth);
unsubs.push(onValue(ref(db,'.info/serverTimeOffset'),s=>{offset=s.val()||0}));
unsubs.push(onValue(ref(db,'.info/connected'),s=>{connected=!!s.val();render();if(connected&&!admin&&session)markPresent().catch(fail)}));
unsubs.push(onValue(S,s=>{let next=s.val();if(!next){session=null;render();return}if(sessionId!==null&&sessionId!==next.id&&!admin){sessionId=next.id;session=next;previousMessageCount=0;render();return}sessionId=next.id;session=next;render();if(connected&&!admin)markPresent().catch(fail)}));
if(admin){document.getElementById('start').onclick=start;document.getElementById('finish').onclick=finish;document.getElementById('reset').onclick=reset;unsubs.push(onValue(ref(db,'presence'),snap=>{presenceData=snap.val()||{};render()}));}else{document.getElementById('composer').onsubmit=sendMessage;document.getElementById('question').onclick=drawQuestion;}
const timer=setInterval(render,250);unsubs.push(()=>clearInterval(timer));}
let marking=false,markedId=null;
async function markPresent(){if(marking||!session||markedId===session.id)return;marking=true;try{if(presence){await onDisconnect(presence).cancel();await remove(presence)}const p=ref(db,`presence/${role}`);await onDisconnect(p).remove();await set(p,{sessionId:session.id,online:true,at:serverTimestamp()});presence=p;markedId=session.id}finally{marking=false}}
function active(){return connected&&session?.status==='RUNNING'&&remain()>0&&sessionId===session.id}
function render(){const clock=document.getElementById('clock');if(!clock)return;const ms=session?.status==='RUNNING'?remain():session?.status==='WAITING'?600000:0,secs=Math.ceil(ms/1000);clock.textContent=`${String(Math.floor(secs/60)).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`;clock.classList.toggle('urgent',session?.status==='RUNNING'&&ms<=60000);const state=document.getElementById('state');if(role==='admin'){state.textContent=!connected?'인터넷 연결 확인 중':!session?'첫 세션을 준비해주세요':({WAITING:'참가자 입장 대기 중',RUNNING:'소개팅 진행 중',FINISHED:'대화 종료'}[session.status]||'상태 확인 필요');{const p=presenceData;for(const r of ['A','B']){const online=connected&&p?.[r]?.online&&p?.[r]?.sessionId===session?.id;const el=document.getElementById(r.toLowerCase()+'Presence');el.textContent=online?'● 접속됨':'○ 대기 중';el.classList.toggle('online',!!online)}document.getElementById('start').disabled=!connected||session?.status!=='WAITING'||!['A','B'].every(r=>p?.[r]?.online&&p?.[r]?.sessionId===session?.id)};document.getElementById('finish').disabled=!connected||session?.status!=='RUNNING';document.getElementById('reset').disabled=!connected;return}
const ended=session?.status==='FINISHED'||session?.status==='RUNNING'&&remain()===0;
state.textContent=!connected?'연결이 끊겼어요. 재연결을 기다리는 중':ended?'대화가 종료되었어요':session?.status==='RUNNING'?'대화 중 💬':'운영진의 시작을 기다려주세요';const ov=document.getElementById('overlay');ov.classList.toggle('hidden',!!session&&!ended&&session.status==='RUNNING'&&connected);document.getElementById('overlayTitle').textContent=ended?'대화 시간이 종료되었습니다':!connected?'연결을 확인하는 중이에요':'잠시만 기다려주세요';document.getElementById('overlayText').textContent=ended?'이제 서로를 확인해주세요! 💌':!connected?'인터넷 연결 후 다시 이어집니다.':'운영진이 소개팅을 시작하면 대화할 수 있어요.';document.getElementById('message').disabled=!active();document.getElementById('send').disabled=!active();document.getElementById('question').disabled=!active();const q=session?.question;const prompt=document.getElementById('prompt');prompt.classList.toggle('show',!!q&&q.sessionId===session?.id);if(q&&q.sessionId===session?.id)prompt.innerHTML=`<strong>🎲 RANDOM QUESTION</strong>${esc(questions[q.current]||'')}`;
const msgs=Object.entries(session?.messages||{}).filter(([,m])=>m.sessionId===session.id).sort((a,b)=>a[0].localeCompare(b[0]));const box=document.getElementById('messages');if(msgs.length!==previousMessageCount){const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<100;box.innerHTML=msgs.length?msgs.map(([,m])=>`<div class="bubble ${m.sender===role?'me':'other'}">${esc(m.text)}</div>`).join(''):'<div class="empty">첫 대화를 시작해보세요 ✨</div>';if(nearBottom)box.scrollTop=box.scrollHeight;previousMessageCount=msgs.length;}}
async function sendMessage(e){e.preventDefault();if(!active())return;const input=document.getElementById('message'),text=input.value.trim();if(!text||text.length>300)return;input.value='';try{await set(push(ref(db,'session/messages')),{sender:role,sessionId:session.id,text,at:serverTimestamp()})}catch(err){input.value=text;fail(err)}}
async function drawQuestion(){if(!active())return;document.getElementById('question').disabled=true;try{const id=session.id;await runTransaction(ref(db,'session/questions'),q=>{if(!q||q.sessionId!==id)q={sessionId:id,used:{},current:null};const available=questions.map((_,i)=>i).filter(i=>!q.used[i]);if(!available.length)return;const pick=available[Math.floor(Math.random()*available.length)];q.used[pick]=true;q.current=pick;q.at=Date.now()+offset;return q},{applyLocally:false});}catch(err){fail(err)}finally{render()}}
async function start(){if(!connected||session?.status!=='WAITING')return;try{const p=(await get(ref(db,'presence'))).val()||{};if(!['A','B'].every(r=>p[r]?.online&&p[r]?.sessionId===session.id))throw Error('A와 B의 접속을 확인해주세요.');const t=now();await runTransaction(S,s=>{if(!s||s.id!==session.id||s.status!=='WAITING')return;s.status='RUNNING';s.startedAt=t;s.endsAt=t+600000;return s},{applyLocally:false})}catch(err){fail(err)}}
async function finish() {
  if (role !== 'admin' || !connected ||
      session?.status !== 'RUNNING') return;

  if (!confirm('지금 대화를 종료할까요?')) return;

  try {
    await set(ref(db, 'session/status'), 'FINISHED');
  } catch (err) {
    fail(err);
  }
}
async function reset(){if(!confirm('현재 커플의 채팅과 질문을 모두 삭제하고 다음 커플을 준비할까요?'))return;try{const next=(session?.id||0)+1;await set(S,{id:next,status:'WAITING',createdAt:serverTimestamp()});await remove(ref(db,'presence'));markedId=null}catch(err){fail(err)}}
